name: CI/CD Self-Hosted

# Only run on pushes to master
on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: self-hosted
    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Docker login for Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Build the Docker image locally
      - name: Build Docker image
        run: |
          docker build -t yourdockerhubuser/greek-encoder:latest .

      # 4. Push Docker image to Docker Hub
      - name: Push Docker image
        run: |
          docker push funmicra/yourapp:latest

      # 5. Deploy using docker-compose on the host
      - name: Deploy container
        run: |
          docker run -d -p 5000:5000 --name Greek-Encoder greek-encoder:latest


